//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADMINISTRATOR
    {
        public string ADMINISTRATOR_ID { get; set; }
        public Nullable<decimal> STATE { get; set; }
        public string NICK_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string AVATAR { get; set; }
        public Nullable<decimal> GENDER { get; set; }
        public Nullable<short> FANS_NUM { get; set; }
        public Nullable<short> FOLLOW_NUM { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SIGNATURE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> TEL { get; set; }
        public string WECHAT { get; set; }
        public string QQ { get; set; }
    }
}
