//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMENTS
    {
        public string COMMENT_ID { get; set; }
        public string COMMENT_CONTENT { get; set; }
        public Nullable<int> LIKES_NUM { get; set; }
    
        public virtual SEND_COMMENT SEND_COMMENT { get; set; }
        public virtual HAS_COMMENT HAS_COMMENT { get; set; }
    }
}
