//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAVORITE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FAVORITE()
        {
            this.HAS_VIDEO = new HashSet<HAS_VIDEO>();
        }
    
        public string FAVORITE_ID { get; set; }
        public string FAVORITE_NAME { get; set; }
        public Nullable<byte> VIDEO_NUM { get; set; }
    
        public virtual HAS_FAVORITES HAS_FAVORITES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAS_VIDEO> HAS_VIDEO { get; set; }
    }
}
