//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HAS_VIDEO
    {
        public string FAVORITE_ID { get; set; }
        public string VIDEO_ID { get; set; }
        public Nullable<System.DateTime> ADD_TIME { get; set; }
    
        public virtual FAVORITE FAVORITE { get; set; }
        public virtual VIDEOS VIDEOS { get; set; }
    }
}
