//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESSAGE_LIBRARY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MESSAGE_LIBRARY()
        {
            this.GET_MESSAGE = new HashSet<GET_MESSAGE>();
        }
    
        public string MESSAGE_ID { get; set; }
        public Nullable<decimal> MESSAGE_TYPE { get; set; }
        public string CONTENT { get; set; }
        public Nullable<System.DateTime> TIME { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GET_MESSAGE> GET_MESSAGE { get; set; }
        public virtual SEND_MESSAGE SEND_MESSAGE { get; set; }
    }
}
