//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVlog.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities2 : DbContext
    {
        public Entities2()
            : base("name=Entities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ADMINISTRATOR> ADMINISTRATOR { get; set; }
        public virtual DbSet<COMMENTS> COMMENTS { get; set; }
        public virtual DbSet<FAVORITE> FAVORITE { get; set; }
        public virtual DbSet<GET_MESSAGE> GET_MESSAGE { get; set; }
        public virtual DbSet<HAS_COMMENT> HAS_COMMENT { get; set; }
        public virtual DbSet<HAS_FAVORITES> HAS_FAVORITES { get; set; }
        public virtual DbSet<HAS_VIDEO> HAS_VIDEO { get; set; }
        public virtual DbSet<HAS_ZONE> HAS_ZONE { get; set; }
        public virtual DbSet<MESSAGE_LIBRARY> MESSAGE_LIBRARY { get; set; }
        public virtual DbSet<RANKING> RANKING { get; set; }
        public virtual DbSet<SEND_COMMENT> SEND_COMMENT { get; set; }
        public virtual DbSet<SEND_MESSAGE> SEND_MESSAGE { get; set; }
        public virtual DbSet<SORT_VIDEO> SORT_VIDEO { get; set; }
        public virtual DbSet<TAG> TAG { get; set; }
        public virtual DbSet<UPLOAD_VIDEO> UPLOAD_VIDEO { get; set; }
        public virtual DbSet<USER_RELATIONSHIP> USER_RELATIONSHIP { get; set; }
        public virtual DbSet<USERS> USERS { get; set; }
        public virtual DbSet<VIDEOS> VIDEOS { get; set; }
        public virtual DbSet<VISIT> VISIT { get; set; }
        public virtual DbSet<ZONE> ZONE { get; set; }
    }
}
