//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public USERS()
        {
            this.GET_MESSAGE = new HashSet<GET_MESSAGE>();
            this.HAS_FAVORITES = new HashSet<HAS_FAVORITES>();
            this.SEND_COMMENT = new HashSet<SEND_COMMENT>();
            this.SEND_MESSAGE = new HashSet<SEND_MESSAGE>();
            this.UPLOAD_VIDEO = new HashSet<UPLOAD_VIDEO>();
            this.USER_RELATIONSHIP = new HashSet<USER_RELATIONSHIP>();
            this.USER_RELATIONSHIP1 = new HashSet<USER_RELATIONSHIP>();
            this.VISIT = new HashSet<VISIT>();
            this.VIDEOS = new HashSet<VIDEOS>();
        }
    
        public string USER_ID { get; set; }
        public Nullable<bool> STATE { get; set; }
        public Nullable<bool> IS_ADMIN { get; set; }
        public string NICK_NAME { get; set; }
        public string PASSWORD { get; set; }
        public string AVATAR { get; set; }
        public Nullable<bool> GENDER { get; set; }
        public Nullable<short> FANS_NUM { get; set; }
        public Nullable<short> FOLLOW_NUM { get; set; }
        public string LOCATION { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string SIGNATURE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<long> TEL { get; set; }
        public string WECHAT { get; set; }
        public string QQ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GET_MESSAGE> GET_MESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAS_FAVORITES> HAS_FAVORITES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEND_COMMENT> SEND_COMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SEND_MESSAGE> SEND_MESSAGE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UPLOAD_VIDEO> UPLOAD_VIDEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_RELATIONSHIP> USER_RELATIONSHIP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USER_RELATIONSHIP> USER_RELATIONSHIP1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISIT> VISIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VIDEOS> VIDEOS { get; set; }
    }
}
