//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace iVlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VIDEOS()
        {
            this.HAS_COMMENT = new HashSet<HAS_COMMENT>();
            this.HAS_VIDEO = new HashSet<HAS_VIDEO>();
            this.SORT_VIDEO = new HashSet<SORT_VIDEO>();
            this.VISIT = new HashSet<VISIT>();
            this.TAG = new HashSet<TAG>();
            this.USERS = new HashSet<USERS>();
        }
    
        public string VIDEO_ID { get; set; }
        public Nullable<bool> PRIVACY { get; set; }
        public string COVER { get; set; }
        public string PATH { get; set; }
        public string DESCRIPTION { get; set; }
        public Nullable<int> LIKES_NUM { get; set; }
        public Nullable<int> PLAY_NUM { get; set; }
        public Nullable<int> COLLECT_NUM { get; set; }
        public Nullable<int> SHARE_NUM { get; set; }
        public Nullable<System.DateTime> UPLOAD_TIME { get; set; }
        public string TITLE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAS_COMMENT> HAS_COMMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HAS_VIDEO> HAS_VIDEO { get; set; }
        public virtual HAS_ZONE HAS_ZONE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SORT_VIDEO> SORT_VIDEO { get; set; }
        public virtual UPLOAD_VIDEO UPLOAD_VIDEO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VISIT> VISIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TAG> TAG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USERS> USERS { get; set; }
    }
}
